




CREATE TABLE Отдел (
 primaryKey UUID NOT NULL,
 ID INT NOT NULL,
 Название VARCHAR(255) NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE Должность (
 primaryKey UUID NOT NULL,
 ID INT NOT NULL,
 Название VARCHAR(255) NOT NULL,
 Оклад VARCHAR(255) NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE ЛКС (
 primaryKey UUID NOT NULL,
 ID INT NOT NULL,
 ФИО VARCHAR(255) NOT NULL,
 Контакты VARCHAR(255) NULL,
 Дата_приема TIMESTAMP(3) NOT NULL,
 Отдел UUID NOT NULL,
 Должность UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE Анкета (
 primaryKey UUID NOT NULL,
 ID INT NOT NULL,
 ФИО VARCHAR(255) NOT NULL,
 Контакты VARCHAR(255) NOT NULL,
 Образование VARCHAR(255) NULL,
 Опыт_работы VARCHAR(255) NULL,
 ЛК VARCHAR(255) NULL,
 Должность UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE ТЧ_отчета (
 primaryKey UUID NOT NULL,
 Результат VARCHAR(255) NOT NULL,
 ЛКС UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE Отчет (
 primaryKey UUID NOT NULL,
 ID INT NOT NULL,
 Дата_проверки TIMESTAMP(3) NOT NULL,
 ТЧ_отчета UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMNETLOCKDATA (
 LockKey VARCHAR(300) NOT NULL,
 UserName VARCHAR(300) NOT NULL,
 LockDate TIMESTAMP(3) NULL,
 PRIMARY KEY (LockKey));


CREATE TABLE STORMSETTINGS (
 primaryKey UUID NOT NULL,
 Module VARCHAR(1000) NULL,
 Name VARCHAR(255) NULL,
 Value TEXT NULL,
 "User" VARCHAR(255) NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMAdvLimit (
 primaryKey UUID NOT NULL,
 "User" VARCHAR(255) NULL,
 Published BOOLEAN NULL,
 Module VARCHAR(255) NULL,
 Name VARCHAR(255) NULL,
 Value TEXT NULL,
 HotKeyData INT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMFILTERSETTING (
 primaryKey UUID NOT NULL,
 Name VARCHAR(255) NOT NULL,
 DataObjectView VARCHAR(255) NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMWEBSEARCH (
 primaryKey UUID NOT NULL,
 Name VARCHAR(255) NOT NULL,
 "Order" INT NOT NULL,
 PresentView VARCHAR(255) NOT NULL,
 DetailedView VARCHAR(255) NOT NULL,
 FilterSetting_m0 UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMFILTERDETAIL (
 primaryKey UUID NOT NULL,
 Caption VARCHAR(255) NOT NULL,
 DataObjectView VARCHAR(255) NOT NULL,
 ConnectMasterProp VARCHAR(255) NOT NULL,
 OwnerConnectProp VARCHAR(255) NULL,
 FilterSetting_m0 UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMFILTERLOOKUP (
 primaryKey UUID NOT NULL,
 DataObjectType VARCHAR(255) NOT NULL,
 Container VARCHAR(255) NULL,
 ContainerTag VARCHAR(255) NULL,
 FieldsToView VARCHAR(255) NULL,
 FilterSetting_m0 UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE UserSetting (
 primaryKey UUID NOT NULL,
 AppName VARCHAR(256) NULL,
 UserName VARCHAR(512) NULL,
 UserGuid UUID NULL,
 ModuleName VARCHAR(1024) NULL,
 ModuleGuid UUID NULL,
 SettName VARCHAR(256) NULL,
 SettGuid UUID NULL,
 SettLastAccessTime TIMESTAMP(3) NULL,
 StrVal VARCHAR(256) NULL,
 TxtVal TEXT NULL,
 IntVal INT NULL,
 BoolVal BOOLEAN NULL,
 GuidVal UUID NULL,
 DecimalVal DECIMAL(20,10) NULL,
 DateTimeVal TIMESTAMP(3) NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE ApplicationLog (
 primaryKey UUID NOT NULL,
 Category VARCHAR(64) NULL,
 EventId INT NULL,
 Priority INT NULL,
 Severity VARCHAR(32) NULL,
 Title VARCHAR(256) NULL,
 Timestamp TIMESTAMP(3) NULL,
 MachineName VARCHAR(32) NULL,
 AppDomainName VARCHAR(512) NULL,
 ProcessId VARCHAR(256) NULL,
 ProcessName VARCHAR(512) NULL,
 ThreadName VARCHAR(512) NULL,
 Win32ThreadId VARCHAR(128) NULL,
 Message VARCHAR(2500) NULL,
 FormattedMessage TEXT NULL,
 PRIMARY KEY (primaryKey));



 ALTER TABLE ЛКС ADD CONSTRAINT FK368da39b18fc87035f9e40e02858d452ceeb79ca FOREIGN KEY (Отдел) REFERENCES Отдел; 
CREATE INDEX Index368da39b18fc87035f9e40e02858d452ceeb79ca on ЛКС (Отдел); 

 ALTER TABLE ЛКС ADD CONSTRAINT FK3ba1c5beabd4c2693251f3699e492bb2804ef0fb FOREIGN KEY (Должность) REFERENCES Должность; 
CREATE INDEX Index3ba1c5beabd4c2693251f3699e492bb2804ef0fb on ЛКС (Должность); 

 ALTER TABLE Анкета ADD CONSTRAINT FK16caa860229eb0a6025173bb760ed70c46542273 FOREIGN KEY (Должность) REFERENCES Должность; 
CREATE INDEX Index16caa860229eb0a6025173bb760ed70c46542273 on Анкета (Должность); 

 ALTER TABLE ТЧ_отчета ADD CONSTRAINT FKf4a1f660615d7d0a29998297047cf3fd40102984 FOREIGN KEY (ЛКС) REFERENCES ЛКС; 
CREATE INDEX Indexf4a1f660615d7d0a29998297047cf3fd40102984 on ТЧ_отчета (ЛКС); 

 ALTER TABLE Отчет ADD CONSTRAINT FK3c9dbe9aac21064c343e474c6bee6ae516edebdc FOREIGN KEY (ТЧ_отчета) REFERENCES ТЧ_отчета; 
CREATE INDEX Index3c9dbe9aac21064c343e474c6bee6ae516edebdc on Отчет (ТЧ_отчета); 

 ALTER TABLE STORMWEBSEARCH ADD CONSTRAINT FKc4378e39870eb056aec84088683297a01d2a6200 FOREIGN KEY (FilterSetting_m0) REFERENCES STORMFILTERSETTING; 

 ALTER TABLE STORMFILTERDETAIL ADD CONSTRAINT FK921d16269835017e2a0d0e29ad6fb175454a70d0 FOREIGN KEY (FilterSetting_m0) REFERENCES STORMFILTERSETTING; 

 ALTER TABLE STORMFILTERLOOKUP ADD CONSTRAINT FKce38ef0db3f01a53acaa49fed8853fb941ad47ba FOREIGN KEY (FilterSetting_m0) REFERENCES STORMFILTERSETTING; 

