//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.HRDepartment
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Анкета.
    /// </summary>
    // *** Start programmer edit section *** (Анкета CustomAttributes)

    // *** End programmer edit section *** (Анкета CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class Анкета : ICSSoft.STORMNET.DataObject
    {
        
        private int fID;
        
        private string fФИО;
        
        private string fКонтакты;
        
        private string fОбразование;
        
        private string fОпыт_работы;
        
        private string fЛК;
        
        private IIS.HRDepartment.Должность fДолжность;
        
        // *** Start programmer edit section *** (Анкета CustomMembers)

        // *** End programmer edit section *** (Анкета CustomMembers)

        
        /// <summary>
        /// ID.
        /// </summary>
        // *** Start programmer edit section *** (Анкета.ID CustomAttributes)

        // *** End programmer edit section *** (Анкета.ID CustomAttributes)
        [NotNull()]
        public virtual int ID
        {
            get
            {
                // *** Start programmer edit section *** (Анкета.ID Get start)

                // *** End programmer edit section *** (Анкета.ID Get start)
                int result = this.fID;
                // *** Start programmer edit section *** (Анкета.ID Get end)

                // *** End programmer edit section *** (Анкета.ID Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Анкета.ID Set start)

                // *** End programmer edit section *** (Анкета.ID Set start)
                this.fID = value;
                // *** Start programmer edit section *** (Анкета.ID Set end)

                // *** End programmer edit section *** (Анкета.ID Set end)
            }
        }
        
        /// <summary>
        /// Контакты.
        /// </summary>
        // *** Start programmer edit section *** (Анкета.Контакты CustomAttributes)

        // *** End programmer edit section *** (Анкета.Контакты CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string Контакты
        {
            get
            {
                // *** Start programmer edit section *** (Анкета.Контакты Get start)

                // *** End programmer edit section *** (Анкета.Контакты Get start)
                string result = this.fКонтакты;
                // *** Start programmer edit section *** (Анкета.Контакты Get end)

                // *** End programmer edit section *** (Анкета.Контакты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Анкета.Контакты Set start)

                // *** End programmer edit section *** (Анкета.Контакты Set start)
                this.fКонтакты = value;
                // *** Start programmer edit section *** (Анкета.Контакты Set end)

                // *** End programmer edit section *** (Анкета.Контакты Set end)
            }
        }
        
        /// <summary>
        /// ЛК.
        /// </summary>
        // *** Start programmer edit section *** (Анкета.ЛК CustomAttributes)

        // *** End programmer edit section *** (Анкета.ЛК CustomAttributes)
        [StrLen(255)]
        public virtual string ЛК
        {
            get
            {
                // *** Start programmer edit section *** (Анкета.ЛК Get start)

                // *** End programmer edit section *** (Анкета.ЛК Get start)
                string result = this.fЛК;
                // *** Start programmer edit section *** (Анкета.ЛК Get end)

                // *** End programmer edit section *** (Анкета.ЛК Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Анкета.ЛК Set start)

                // *** End programmer edit section *** (Анкета.ЛК Set start)
                this.fЛК = value;
                // *** Start programmer edit section *** (Анкета.ЛК Set end)

                // *** End programmer edit section *** (Анкета.ЛК Set end)
            }
        }
        
        /// <summary>
        /// Образование.
        /// </summary>
        // *** Start programmer edit section *** (Анкета.Образование CustomAttributes)

        // *** End programmer edit section *** (Анкета.Образование CustomAttributes)
        [StrLen(255)]
        public virtual string Образование
        {
            get
            {
                // *** Start programmer edit section *** (Анкета.Образование Get start)

                // *** End programmer edit section *** (Анкета.Образование Get start)
                string result = this.fОбразование;
                // *** Start programmer edit section *** (Анкета.Образование Get end)

                // *** End programmer edit section *** (Анкета.Образование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Анкета.Образование Set start)

                // *** End programmer edit section *** (Анкета.Образование Set start)
                this.fОбразование = value;
                // *** Start programmer edit section *** (Анкета.Образование Set end)

                // *** End programmer edit section *** (Анкета.Образование Set end)
            }
        }
        
        /// <summary>
        /// Опыт_работы.
        /// </summary>
        // *** Start programmer edit section *** (Анкета.Опыт_работы CustomAttributes)

        // *** End programmer edit section *** (Анкета.Опыт_работы CustomAttributes)
        [StrLen(255)]
        public virtual string Опыт_работы
        {
            get
            {
                // *** Start programmer edit section *** (Анкета.Опыт_работы Get start)

                // *** End programmer edit section *** (Анкета.Опыт_работы Get start)
                string result = this.fОпыт_работы;
                // *** Start programmer edit section *** (Анкета.Опыт_работы Get end)

                // *** End programmer edit section *** (Анкета.Опыт_работы Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Анкета.Опыт_работы Set start)

                // *** End programmer edit section *** (Анкета.Опыт_работы Set start)
                this.fОпыт_работы = value;
                // *** Start programmer edit section *** (Анкета.Опыт_работы Set end)

                // *** End programmer edit section *** (Анкета.Опыт_работы Set end)
            }
        }
        
        /// <summary>
        /// ФИО.
        /// </summary>
        // *** Start programmer edit section *** (Анкета.ФИО CustomAttributes)

        // *** End programmer edit section *** (Анкета.ФИО CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string ФИО
        {
            get
            {
                // *** Start programmer edit section *** (Анкета.ФИО Get start)

                // *** End programmer edit section *** (Анкета.ФИО Get start)
                string result = this.fФИО;
                // *** Start programmer edit section *** (Анкета.ФИО Get end)

                // *** End programmer edit section *** (Анкета.ФИО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Анкета.ФИО Set start)

                // *** End programmer edit section *** (Анкета.ФИО Set start)
                this.fФИО = value;
                // *** Start programmer edit section *** (Анкета.ФИО Set end)

                // *** End programmer edit section *** (Анкета.ФИО Set end)
            }
        }
        
        /// <summary>
        /// Анкета.
        /// </summary>
        // *** Start programmer edit section *** (Анкета.Должность CustomAttributes)

        // *** End programmer edit section *** (Анкета.Должность CustomAttributes)
        [PropertyStorage(new string[] {
                "Должность"})]
        [NotNull()]
        public virtual IIS.HRDepartment.Должность Должность
        {
            get
            {
                // *** Start programmer edit section *** (Анкета.Должность Get start)

                // *** End programmer edit section *** (Анкета.Должность Get start)
                IIS.HRDepartment.Должность result = this.fДолжность;
                // *** Start programmer edit section *** (Анкета.Должность Get end)

                // *** End programmer edit section *** (Анкета.Должность Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Анкета.Должность Set start)

                // *** End programmer edit section *** (Анкета.Должность Set start)
                this.fДолжность = value;
                // *** Start programmer edit section *** (Анкета.Должность Set end)

                // *** End programmer edit section *** (Анкета.Должность Set end)
            }
        }
    }
}
