//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.HRDepartment
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Отдел.
    /// </summary>
    // *** Start programmer edit section *** (Отдел CustomAttributes)

    // *** End programmer edit section *** (Отдел CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОтделE", new string[] {
            "ID as \'ID\'",
            "Название as \'Название\'"})]
    [View("ОтделL", new string[] {
            "ID as \'ID\'",
            "Название as \'Название\'"})]
    public class Отдел : ICSSoft.STORMNET.DataObject
    {
        
        private int fID;
        
        private string fНазвание;
        
        // *** Start programmer edit section *** (Отдел CustomMembers)

        // *** End programmer edit section *** (Отдел CustomMembers)

        
        /// <summary>
        /// ID.
        /// </summary>
        // *** Start programmer edit section *** (Отдел.ID CustomAttributes)

        // *** End programmer edit section *** (Отдел.ID CustomAttributes)
        [NotNull()]
        public virtual int ID
        {
            get
            {
                // *** Start programmer edit section *** (Отдел.ID Get start)

                // *** End programmer edit section *** (Отдел.ID Get start)
                int result = this.fID;
                // *** Start programmer edit section *** (Отдел.ID Get end)

                // *** End programmer edit section *** (Отдел.ID Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Отдел.ID Set start)

                // *** End programmer edit section *** (Отдел.ID Set start)
                this.fID = value;
                // *** Start programmer edit section *** (Отдел.ID Set end)

                // *** End programmer edit section *** (Отдел.ID Set end)
            }
        }
        
        /// <summary>
        /// Название.
        /// </summary>
        // *** Start programmer edit section *** (Отдел.Название CustomAttributes)

        // *** End programmer edit section *** (Отдел.Название CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string Название
        {
            get
            {
                // *** Start programmer edit section *** (Отдел.Название Get start)

                // *** End programmer edit section *** (Отдел.Название Get start)
                string result = this.fНазвание;
                // *** Start programmer edit section *** (Отдел.Название Get end)

                // *** End programmer edit section *** (Отдел.Название Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Отдел.Название Set start)

                // *** End programmer edit section *** (Отдел.Название Set start)
                this.fНазвание = value;
                // *** Start programmer edit section *** (Отдел.Название Set end)

                // *** End programmer edit section *** (Отдел.Название Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОтделE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОтделE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОтделE", typeof(IIS.HRDepartment.Отдел));
                }
            }
            
            /// <summary>
            /// "ОтделL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОтделL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОтделL", typeof(IIS.HRDepartment.Отдел));
                }
            }
        }
    }
}
