//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.HRDepartment
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ТЧ_отчета.
    /// </summary>
    // *** Start programmer edit section *** (ТЧ_отчета CustomAttributes)

    // *** End programmer edit section *** (ТЧ_отчета CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class ТЧ_отчета : ICSSoft.STORMNET.DataObject
    {
        
        private string fРезультат;
        
        private IIS.HRDepartment.ЛКС fЛКС;
        
        private IIS.HRDepartment.DetailArrayOfОтчет fОтчет;
        
        // *** Start programmer edit section *** (ТЧ_отчета CustomMembers)

        // *** End programmer edit section *** (ТЧ_отчета CustomMembers)

        
        /// <summary>
        /// Результат.
        /// </summary>
        // *** Start programmer edit section *** (ТЧ_отчета.Результат CustomAttributes)

        // *** End programmer edit section *** (ТЧ_отчета.Результат CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string Результат
        {
            get
            {
                // *** Start programmer edit section *** (ТЧ_отчета.Результат Get start)

                // *** End programmer edit section *** (ТЧ_отчета.Результат Get start)
                string result = this.fРезультат;
                // *** Start programmer edit section *** (ТЧ_отчета.Результат Get end)

                // *** End programmer edit section *** (ТЧ_отчета.Результат Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧ_отчета.Результат Set start)

                // *** End programmer edit section *** (ТЧ_отчета.Результат Set start)
                this.fРезультат = value;
                // *** Start programmer edit section *** (ТЧ_отчета.Результат Set end)

                // *** End programmer edit section *** (ТЧ_отчета.Результат Set end)
            }
        }
        
        /// <summary>
        /// ТЧ_отчета.
        /// </summary>
        // *** Start programmer edit section *** (ТЧ_отчета.ЛКС CustomAttributes)

        // *** End programmer edit section *** (ТЧ_отчета.ЛКС CustomAttributes)
        [PropertyStorage(new string[] {
                "ЛКС"})]
        [NotNull()]
        public virtual IIS.HRDepartment.ЛКС ЛКС
        {
            get
            {
                // *** Start programmer edit section *** (ТЧ_отчета.ЛКС Get start)

                // *** End programmer edit section *** (ТЧ_отчета.ЛКС Get start)
                IIS.HRDepartment.ЛКС result = this.fЛКС;
                // *** Start programmer edit section *** (ТЧ_отчета.ЛКС Get end)

                // *** End programmer edit section *** (ТЧ_отчета.ЛКС Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧ_отчета.ЛКС Set start)

                // *** End programmer edit section *** (ТЧ_отчета.ЛКС Set start)
                this.fЛКС = value;
                // *** Start programmer edit section *** (ТЧ_отчета.ЛКС Set end)

                // *** End programmer edit section *** (ТЧ_отчета.ЛКС Set end)
            }
        }
        
        /// <summary>
        /// ТЧ_отчета.
        /// </summary>
        // *** Start programmer edit section *** (ТЧ_отчета.Отчет CustomAttributes)

        // *** End programmer edit section *** (ТЧ_отчета.Отчет CustomAttributes)
        public virtual IIS.HRDepartment.DetailArrayOfОтчет Отчет
        {
            get
            {
                // *** Start programmer edit section *** (ТЧ_отчета.Отчет Get start)

                // *** End programmer edit section *** (ТЧ_отчета.Отчет Get start)
                if ((this.fОтчет == null))
                {
                    this.fОтчет = new IIS.HRDepartment.DetailArrayOfОтчет(this);
                }
                IIS.HRDepartment.DetailArrayOfОтчет result = this.fОтчет;
                // *** Start programmer edit section *** (ТЧ_отчета.Отчет Get end)

                // *** End programmer edit section *** (ТЧ_отчета.Отчет Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧ_отчета.Отчет Set start)

                // *** End programmer edit section *** (ТЧ_отчета.Отчет Set start)
                this.fОтчет = value;
                // *** Start programmer edit section *** (ТЧ_отчета.Отчет Set end)

                // *** End programmer edit section *** (ТЧ_отчета.Отчет Set end)
            }
        }
    }
}
